# Nueva EERR_STRUCTURE extraida de EJEMPLO EERR.xlsx (hoja EERR LOS NA)
# Formato: (nombre, is_header, parent, bold, bg_color, level)
# level: 0=totales principales, 1=subtotales, 2=agrupadores internos, 3=partidas hoja

EERR_STRUCTURE = [
    ('ESTADO DE RESULTADOS', True, None, True, None, 0),
    ('PARTIDAS', True, None, True, None, 0),
    ('Total Ingresos', True, None, True, 'FF6AD9E8', 0),
    ('Subtotal Ingresos por Venta de Mercancia', True, None, True, None, 1),
    ('Ingresos por venta de mercancias', False, None, False, None, 3),
    ('Devoluciones sobre ventas', False, None, False, None, 3),
    ('Descuentos sobre ventas', False, None, False, None, 3),
    ('Subtotal Ingresos por Servicios', True, None, True, None, 1),
    ('Ingresos por servicios del café', False, None, False, None, 3),
    ('Ingresos por zona FIT', False, None, False, None, 3),
    ('Ingresos por fletes', False, None, False, None, 3),
    ('Subtotal Ingresos por Eventos', True, None, True, None, 1),
    ('Ingresos por eventos', False, None, False, None, 3),
    ('Subtotal Ingresos por Taller', True, None, True, None, 1),
    ('Ingresos por taller', False, None, False, None, 3),
    ('Total Costo de Ventas', True, None, True, None, 0),
    ('Subtotal Costo de Ventas por Mercancia', True, None, True, None, 1),
    ('Costos de venta por mercancia', False, None, False, None, 3),
    ('Subtotal Costo de Ventas por Servicios', True, None, True, None, 1),
    ('Costo de venta por servicio del café', False, None, False, None, 3),
    ('Subtotal Costo de Ventas por Eventos', True, None, True, None, 1),
    ('Costo de ventas por eventos', False, None, False, None, 3),
    ('Utilidad Bruta por Venta de Mercancia y Taller', True, None, True, 'FF66FF66', 0),
    ('Utilidad Bruta por Servicios', True, None, True, 'FF66FF66', 0),
    ('Utilidad Bruta por Eventos', True, None, True, 'FF66FF66', 0),
    ('Utilidad Bruta', True, None, True, 'FF66FF66', 0),
    ('Total Gastos Operacionales', True, None, True, None, 0),
    ('Subtotal Gastos de Administración', True, None, True, None, 1),
    ('Gastos de servicios públicos (Agua, luz, Aseo Urbano)', False, None, False, None, 3),
    ('Gastos de servicios de telefonía e internet', False, None, False, None, 3),
    ('Gastos de alquiler del local', False, None, False, None, 3),
    ('Gastos de Condominio', False, None, False, None, 3),
    ('Gastos de asistencia outsorcing', False, None, False, None, 3),
    ('Gastos de alquiler de bienes muebles', False, None, False, None, 3),
    ('Gastos de artículos de oficina', False, None, False, None, 3),
    ('Gastos de artículos de limpieza e higiene', False, None, False, None, 3),
    ('Gastos de alimentos y bebidas', False, None, False, None, 3),
    ('Gastos de envíos y encomiendas administrativas', False, None, False, None, 3),
    ('Gastos de honorarios profesionales', False, None, False, None, 3),
    ('Gastos de estacionamiento', False, None, False, None, 3),
    ('Gastos de gestoría', False, None, False, None, 3),
    ('Gastos legales', False, None, False, None, 3),
    ('Gastos de taxi, transporte y/o delivery', False, None, False, None, 3),
    ('Gastos de suministros para taller', False, None, False, None, 3),
    ('Gastos de suministros del café', False, None, False, None, 3),
    ('Gastos por fiestas, festejos y/o reuniones', False, None, False, None, 3),
    ('Gastos de vigilancia', False, None, False, None, 3),
    ('Gastos de retenciones no descontadas', False, None, False, None, 3),
    ('Mantenimiento y reparaciones', False, None, False, None, 3),
    ('Viáticos administrativos', False, None, False, None, 3),
    ('Gastos de seguro', False, None, False, None, 3),
    ('Gastos de impuestos, tasas y contribuciones', False, None, False, None, 3),
    ('Depreciaciones, deterioro y Amortización', False, None, False, None, 3),
    ('Gasto por impuesto a las pensiones', False, None, False, None, 3),
    ('Gastos de IGTF', False, None, False, None, 3),
    ('Gastos de comisiones bancarias', False, None, False, None, 3),
    ('Gastos Bancarios', False, None, False, None, 3),
    ('Gastos de intereses sobre préstamos', False, None, False, None, 3),
    ('Subtotal Gastos de Recursos Humanos', True, None, True, None, 1),
    ('Gastos de sueldos y salarios empleados y directivos', True, None, False, None, 2),
    ('Gastos de sueldos y salarios empleados', False, None, False, None, 3),
    ('Gastos de sueldos y salarios directivos', False, None, False, None, 3),
    ('Gastos de horas extras, feriados y bono nocturno', False, None, False, None, 3),
    ('Gastos de Bono de alimentación empleados', False, None, False, None, 3),
    ('Gastos de Bono de alimentación directivos', False, None, False, None, 3),
    ('Gastos de complementos empleados y directivos', True, None, False, None, 2),
    ('Gastos de complemento de sueldos y salarios empleados', False, None, False, None, 3),
    ('Gastos de complemento de sueldos y salarios directivos', False, None, False, None, 3),
    ('Gastos de personal externo', True, None, False, None, 2),
    ('Gastos de servicios de personal externo', False, None, False, None, 3),
    ('Gastos de pasivos laborales vacaciones', True, None, False, None, 2),
    ('Gastos de vacaciones empleados', False, None, False, None, 3),
    ('Gastos de vacaciones directivos', False, None, False, None, 3),
    ('Gastos de complemento de vacaciones empleados', False, None, False, None, 3),
    ('Gastos de complemento de vacaciones directivos', False, None, False, None, 3),
    ('Gastos de pasivos laborales utilidades', True, None, False, None, 2),
    ('Gastos de bono vacacional empleados', False, None, False, None, 3),
    ('Gastos de bono vacacional directivos', False, None, False, None, 3),
    ('Gastos de complemento bono vacacional empleados', False, None, False, None, 3),
    ('Gastos de complemento bono vacacional directivos', False, None, False, None, 3),
    ('Gastos de utilidades empleados', False, None, False, None, 3),
    ('Gastos de utilidades directivos', False, None, False, None, 3),
    ('Gastos de complemento de utilidades empleados', False, None, False, None, 3),
    ('Gastos de complemento de utilidades directivos', False, None, False, None, 3),
    ('Gastos de pasivos laborales prestaciones e intereses', True, None, False, None, 2),
    ('Gastos de prestaciones sociales empleados', False, None, False, None, 3),
    ('Gastos de prestaciones sociales directivos', False, None, False, None, 3),
    ('Gastos de complemento de prestaciones sociales empleados', False, None, False, None, 3),
    ('Gastos de complemento de prestaciones sociales directivos', False, None, False, None, 3),
    ('Gastos de intereses sobres prestaciones sociales empleados', False, None, False, None, 3),
    ('Gastos de intereses sobres prestaciones sociales directivos', False, None, False, None, 3),
    ('Gastos de complemento de intereses sobre prestaciones sociales empleados', False, None, False, None, 3),
    ('Gastos de complemento de intereses sobre prestaciones sociales directivos', False, None, False, None, 3),
    ('Gastos de pasivos laborales aportes', True, None, False, None, 2),
    ('Gastos de aporte patronal IVSS', False, None, False, None, 3),
    ('Gastos de aporte patronal SPF', False, None, False, None, 3),
    ('Gastos de aporte patronal FAOV', False, None, False, None, 3),
    ('Gastos de aporte patronal INCES', False, None, False, None, 3),
    ('Gastos de bono de guardería', False, None, False, None, 3),
    ('Gastos de pasivos laborales HCM', True, None, False, None, 2),
    ('Gastos de póliza HCM', False, None, False, None, 3),
    ('Gastos de salud y seguridad laboral', False, None, False, None, 3),
    ('Gastos de salud y seguridad laboral dotación', False, None, False, None, 3),
    ('Gastos de uniformes y dotación al personal', False, None, False, None, 3),
    ('Gastos de salud y seguridad laboral fiestas y agasajos', True, None, False, None, 2),
    ('Gastos de fiestas y agasajos al personal', False, None, False, None, 3),
    ('Otros gastos de personal', True, None, False, None, 2),
    ('Gastos de otros bonos empleados', False, None, False, None, 3),
    ('Gastos de transporte del personal', False, None, False, None, 3),
    ('Gastos de donaciones y obsequios al personal', False, None, False, None, 3),
    ('Gastos de capacitación al personal', False, None, False, None, 3),
    ('Subtotal Gastos de Comercialización y Logistica', True, None, True, None, 1),
    ('Gastos de viáticos comerciales', False, None, False, None, 3),
    ('Gastos de comisiones empleados', False, None, False, None, 3),
    ('Gastos de comisiones empleados del taller', False, None, False, None, 3),
    ('Gastos de comisiones por venta de personal externo', False, None, False, None, 3),
    ('Gastos de fletes y envios no asociados al costo', False, None, False, None, 3),
    ('Otros gastos no asociados al costo', False, None, False, None, 3),
    ('Gastos por combustible', False, None, False, None, 3),
    ('Gastos de representación', False, None, False, None, 3),
    ('Gastos por garantia', False, None, False, None, 3),
    ('Gastos por suscripciones', False, None, False, None, 3),
    ('Gastos de Stand y/o ferias comerciales', False, None, False, None, 3),
    ('Subtotal Gastos de Mercadeo', True, None, True, None, 1),
    ('Gastos de redes sociales', False, None, False, None, 3),
    ('Gastos de medios publicitarios', False, None, False, None, 3),
    ('Gastos de impresiones de material gráfico', False, None, False, None, 3),
    ('Otros gastos de publicidad y promoción', False, None, False, None, 3),
    ('Gastos de patrocinio y donación', False, None, False, None, 3),
    ('Gastos de patrocinio, donación y/o obsequios en efectivo', False, None, False, None, 3),
    ('Gastos de patrocinio, donación y/o obsequios en productos', False, None, False, None, 3),
    ('Gastos de viáticos por eventos', False, None, False, None, 3),
    ('Gastos de materiales y servicios por eventos', False, None, False, None, 3),
    ('Gastos de alimentos y bebidas por eventos', False, None, False, None, 3),
    ('Gastos de personal por eventos', False, None, False, None, 3),
    ('Gastos de patrocinio, donación y/o obseq por eventos', False, None, False, None, 3),
    ('Gastos de TI+I', True, None, True, None, 1),
    ('Gastos de página web', False, None, False, None, 3),
    ('Gastos de desarrollo', False, None, False, None, 3),
    ('Utilidad antes de Comisiones por Ventas', True, None, True, 'FF66FF66', 0),
    ('Gastos de comisiones por ventas', False, None, False, None, 3),
    ('Gastos de comisiones por ventas taller', False, None, False, None, 3),
    ('Utilidad después de Comisiones por Ventas', True, None, True, 'FF66FF66', 0),
    ('Utilidad antes de intereses, impuestos, depreciación y amortización (EBITDA)', True, None, True, 'FF66FF66', 0),
    ('Utilidad antes de Intereses e Impuestos (EBIT)', True, None, True, 'FF66FF66', 0),
    ('Otros Gastos no Operacionales', True, None, True, None, 0),
    ('Faltante en Ventas', False, None, False, None, 3),
    ('Pérdida en venta de activos', False, None, False, None, 3),
    ('Pérdida en siniestro de activos', False, None, False, None, 3),
    ('Pérdida en tasa cambiaria', False, None, False, None, 3),
    ('Pérdida por diferencia en pagos', False, None, False, None, 3),
    ('Multas', False, None, False, None, 3),
    ('Faltante y deterioro de inventarios', False, None, False, None, 3),
    ('Total Gastos Operacionales y No Operacionales', True, None, True, 'FFFFFF00', 0),
    ('Otros Ingresos no Operacionales', True, None, True, None, 0),
    ('Ingresos por alquileres', False, None, False, None, 3),
    ('Ingresos por intereses', False, None, False, None, 3),
    ('Ingresos por comisiones', False, None, False, None, 3),
    ('Ingresos por servicios administrativos', False, None, False, None, 3),
    ('Sobrante en ventas', False, None, False, None, 3),
    ('Sobrante de inventarios', False, None, False, None, 3),
    ('Ganancia en venta de activos', False, None, False, None, 3),
    ('Ganancia por tasa cambiaria', False, None, False, None, 3),
    ('Ganancia por diferencias en pagos', False, None, False, None, 3),
    ('Utilidad Neta', True, None, True, 'FF66FF66', 0),
    ('ISLR', True, None, True, None, 0),
    ('Utilidad Neta despues de ISLR', True, None, True, 'FF66FF66', 0),
]
